install:
  - set QTDIR=C:\Qt\5.13\msvc2017
  - set PATH=%PATH%;%QTDIR%\bin
  - dir C:\Qt\5.13\
build_script:
  - qmake CobraBot.pro
  - NMAKE
  - cd release
  
artifacts:
  - path: release\CobraBot.exe
