install:
  - set QTDIR=C:\Qt\5.13.2\mingw73_64
   - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - qmake CobraBot.pro
  - mingw32-make
  - cd release
  
artifacts:
  - path: release\CobraBot.exe
