install:
  - cmd: set QTDIR=C:\Qt\5.13.2\msvc2015_64
  - cmd: set PATH=%PATH%;%QTDIR%\bin
build_script:
  - cmd: qmake CobraBot.pro
  - cmd: NMAKE
  - cmd: cd release
  
artifacts:
  - path: release\CobraBot.exe
