install:
  - set QTDIR=C:\Qt\5.13.2\msvc2015_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - qmake CobraBot.pro
  - NMAKE
  - cd release
  
artifacts:
  - path: release\CobraBot.exe
